### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by yln** [opensource-apple/objc4#3]
Please provide instructions for compiling. I am struggling to compile the latest version (objc-647).

I tried to compile on OS X 10.10.5 with Xcode 7.0.1 using the MacOSX10.10.sdk (sdk 10.10 does not ship with Xcode 7 anymore) and the missing headers from https://github.com/samdmarshall/OSXPrivateSDK.

**Comment by opensource-apple** [comment]
Please contact http://opensource.apple.com/ , opensource@apple.com or http://lists.apple.com/ .

**Comment by chunlea** [comment]
@yln check this link: https://github.com/ourui/objc4-647 . It works.
